# GET con y sin producto
GET http://localhost:3080/api/v1/products/

### GET hi
GET http://localhost:3080/

### GET health
GET http://localhost:3080/health

###POST con ID unico
POST http://localhost:3080/api/v1/products HTTP/1.1
Content-Type: application/json

{
    "name": "Men's short-sleeved shirt",
    "description": "Soft and lightweight cotton shirt for warm days.",
    "availableUnits": 20,
    "price": 29.99,
    "category": "Men"
}


###PATCH con ID unico
PATCH  http://localhost:3080/api/v1/products/6446f7daf9198b109836d94d HTTP/1.1
Content-Type: application/json

{
    "name":"short"
}

###DELETE con ID unico
DELETE http://localhost:3080/api/v1/products/6446f7daf9198b109836d94d HTTP/1.1

# [
#   {
#     "name": "Men's short-sleeved shirt",
#     "description": "Soft and lightweight cotton shirt for warm days.",
#     "availableUnits": 20,
#     "price": 29.99,
#     "category": "Men"
#   },
#   {
#     "name": "Women's pleated skirt",
#     "description": "Elegant skirt with a unique pleated pattern.",
#     "availableUnits": 15,
#     "price": 39.99,
#     "category": "Women"
#   },
#   {
#     "name": "Children's winter jacket",
#     "description": "Padded jacket with a hood to protect children from the cold.",
#     "availableUnits": 10,
#     "price": 49.99,
#     "category": "Children"
#   }
# ]
